export const VIEW_CONFIG_UPDATE = 'VIEW_CONFIG_UPDATE';
export const VIEW_CONFIG_CHANGE_MENU = 'VIEW_CONFIG_CHANGE_MENU';
export const VIEW_CONFIG_CHANGE_SUB_MENU = 'VIEW_CONFIG_CHANGE_SUB_MENU';

export const EDITOR_START_EDIT = 'EDITOR_START_EDIT';
export const EDITOR_END_EDIT = 'EDITOR_END_EDIT';
export const EDITOR_SET_INITIAL_VALUES = 'EDITOR_SET_INITIAL_VALUES';
export const EDITOR_UPDATE_VALUES = 'EDITOR_UPDATE_VALUES';
export const EDITOR_RESET_VALUES = 'EDITOR_RESET_VALUES';
export const EDITOR_SUBMIT_EDIT = 'EDITOR_SUBMIT_EDIT';
export const EDITOR_WAIT_SUBMIT = 'EDITOR_WAIT_SUBMIT';
export const EDITOR_END_SUBMIT = 'EDITOR_END_SUBMIT';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const AD_LIST_REQUEST = 'AD_LIST_REQUEST';
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS';
export const AD_LIST_FAILURE = 'AD_LIST_FAILURE';

export const AD_EXPORT_REQUEST = 'AD_EXPORT_REQUEST';
export const AD_EXPORT_SUCCESS = 'AD_EXPORT_SUCCESS';
export const AD_EXPORT_FAILURE = 'AD_EXPORT_FAILURE';

export const AD_BATCH_SETTLE_REQUEST = 'AD_BATCH_SETTLE_REQUEST';
export const AD_BATCH_SETTLE_SUCCESS = 'AD_BATCH_SETTLE_SUCCESS';
export const AD_BATCH_SETTLE_FAILURE = 'AD_BATCH_SETTLE_FAILURE';

export const AD_BATCH_REJECT_REQUEST = 'AD_BATCH_REJECT_REQUEST';
export const AD_BATCH_REJECT_SUCCESS = 'AD_BATCH_REJECT_SUCCESS';
export const AD_BATCH_REJECT_FAILURE = 'AD_BATCH_REJECT_FAILURE';
export const AD_REJECT_REMARK_CHANGE = 'AD_REJECT_REMARK_CHANGE';

export const AD_REJECT_MODAL_SHOW = 'AD_REJECT_MODAL_SHOW';
export const AD_REJECT_MODAL_HIDE = 'AD_REJECT_MODAL_HIDE';

export const AD_ACTIVITY_IMG_SHOW = 'AD_ACTIVITY_IMG_SHOW';
export const AD_ACTIVITY_IMG_HIDE = 'AD_ACTIVITY_IMG_HIDE';

export const AD_SELECT_KEY_REQUEST = 'AD_SELECT_KEY_REQUEST';

export const AD_RATE_SETTING_REQUEST = 'AD_RATE_SETTING_REQUEST';
export const AD_RATE_SETTING_SUCCESS = 'AD_RATE_SETTING_SUCCESS';
export const AD_RATE_SETTING_FAILURE = 'AD_RATE_SETTING_FAILURE';
export const AD_RATE_SETTING_CHANGE = 'AD_RATE_SETTING_CHANGE';

export const AD_RATE_MODAL_SHOW = 'AD_RATE_MODAL_SHOW';
export const AD_RATE_MODAL_HIDE = 'AD_RATE_MODAL_HIDE';
