export const SET_VIEW_CONFIG = 'SET_VIEW_CONFIG';

export const IDENTIFY_REG_REQUEST = 'IDENTIFY_REG_REQUEST';
export const IDENTIFY_REG_SUCCESS = 'IDENTIFY_REG_SUCCESS';
export const IDENTIFY_REG_FAILURE = 'IDENTIFY_REG_FAILURE';
export const REG_COUNTDOWN_STOPPED = 'REG_COUNTDOWN_STOPPED';

/* 网赚任务 start */
export const TASKS_LIST_REQUEST = 'TASKS_LIST_REQUEST';
export const TASKS_LIST_SUCCESS = 'TASKS_LIST_SUCCESS';
export const TASKS_LIST_FAILURE = 'TASKS_LIST_FAILURE';

export const TASK_DETAIL_REQUEST = 'TASK_DETAIL_REQUEST';
export const TASK_DETAIL_SUCCESS = 'TASK_DETAIL_SUCCESS';
export const TASK_DETAIL_FAILURE = 'TASK_DETAIL_FAILURE';

export const TASK_SUBMIT_REQUEST = 'TASK_SUBMIT_REQUEST';
export const TASK_SUBMIT_SUCCESS = 'TASK_SUBMIT_SUCCESS';
export const TASK_SUBMIT_FAILURE = 'TASK_SUBMIT_FAILURE';

export const TASKS_TAB_CHANGE = 'TASKS_TAB_CHANGE';
export const TASKS_REGISTER_SHOW = 'TASKS_REGISTER_SHOW';
export const TASKS_REGISTER_HIDE = 'TASKS_REGISTER_HIDE';
export const TASKS_APPLY_MODAL_SHOW = 'TASKS_APPLY_MODAL_SHOW';
export const TASKS_APPLY_MODAL_HIDE = 'TASKS_APPLY_MODAL_HIDE';
export const TASKS_SHARE_MODAL_SHOW = 'TASKS_SHARE_MODAL_SHOW';
export const TASKS_SHARE_MODAL_HIDE = 'TASKS_SHARE_MODAL_HIDE';

// 显示/隐藏手机号绑定微信弹窗
export const TASKS_BIND_MODAL_SHOW = 'TASKS_BIND_MODAL_SHOW';
export const TASKS_BIND_MODAL_HIDE = 'TASKS_BIND_MODAL_HIDE';

// 微信号与手机号的绑定
export const TASKS_BIND_RELATION_REQUEST = 'TASKS_BIND_RELATION_REQUEST'
export const TASKS_BIND_RELATION_SUCCESS = 'TASKS_BIND_RELATION_SUCCESS'
export const TASKS_BIND_RELATION_FAILURE = 'TASKS_BIND_RELATION_FAILURE'

// 获取用户信息
export const WX_USER_INFO_REQUEST = 'WX_USER_INFO_REQUEST';
export const WX_USER_INFO_SUCCESS = 'WX_USER_INFO_SUCCESS';
export const WX_USER_INFO_FAILURE = 'WX_USER_INFO_FAILURE';

// 注册
export const TASKS_REGISTER_REQUEST = 'TASKS_REGISTER_REQUEST'
export const TASKS_REGISTER_SUCCESS = 'TASKS_REGISTER_SUCCESS'
export const TASKS_REGISTER_FAILURE = 'TASKS_REGISTER_FAILURE'

// 显示/隐藏做任务的分享图片弹框
export const TASKS_IMG_MODAL_SHOW = 'TASKS_IMG_MODAL_SHOW'
export const TASKS_IMG_MODAL_HIDE = 'TASKS_IMG_MODAL_HIDE'

// 获取收入列表
export const TASKS_GET_INCOME_LIST_REQUEST = 'TASKS_GET_INCOME_LIST_REQUEST'
export const TASKS_GET_INCOME_LIST_SUCCESS = 'TASKS_GET_INCOME_LIST_SUCCESS'
export const TASKS_GET_INCOME_LIST_FAILURE = 'TASKS_GET_INCOME_LIST_FAILURE'

export const TASKS_CHANGE_INCOME_TAB = 'TASKS_CHANGE_INCOME_TAB'; // 切换收益 tab

// 素材审核列表
export const TASKS_CHECK_LIST_REQUEST = 'TASKS_CHECK_LIST_REQUEST';
export const TASKS_CHECK_LIST_SUCCESS = 'TASKS_CHECK_LIST_SUCCESS';
export const TASKS_CHECK_LIST_FAILURE = 'TASKS_CHECK_LIST_FAILURE';

export const TASKS_UPLOAD_ORDER_REQUEST = 'TASKS_UPLOAD_ORDER_REQUEST'; // 上传订单材料
export const TASKS_UPLOAD_ORDER_SUCCESS = 'TASKS_UPLOAD_ORDER_SUCCESS';
export const TASKS_UPLOAD_ORDER_FAILURE = 'TASKS_UPLOAD_ORDER_FAILURE';
export const TASKS_GET_INCOME_REQUEST = 'TASKS_GET_INCOME_REQUEST'; // 获取累计收益
export const TASKS_GET_INCOME_SUCCESS = 'TASKS_GET_INCOME_SUCCESS';
export const TASKS_BROADCAST_REQUEST = 'TASKS_BROADCAST_REQUEST'; // 收益轮播信息
export const TASKS_BROADCAST_SUCCESS = 'TASKS_BROADCAST_SUCCESS';
export const TASKS_APPLY_AGENT_REQUEST = 'TASKS_APPLY_AGENT_REQUEST'; // 升级代理
export const TASKS_APPLY_AGENT_SUCCESS = 'TASKS_APPLY_AGENT_SUCCESS'
export const TASKS_CHANGE_REGISTER_INFO = 'TASKS_CHANGE_REGISTER_INFO'; // 修改注册时填写的信息
export const TASKS_GET_RED_BAG_REQUEST = 'TASKS_GET_RED_BAG_REQUEST'; // 获取红包详情
export const TASKS_GET_RED_BAG_SUCCESS = 'TASKS_GET_RED_BAG_SUCCESS';
export const TASKS_GET_RED_BAG_FAILURE = 'TASKS_GET_RED_BAG_FAILURE';
export const TASKS_RED_BAG_MODAL_HIDE = 'TASKS_RED_BAG_MODAL_HIDE'; // 隐藏红包弹窗
export const TASKS_RED_BAG_MODAL_SHOW = 'TASKS_RED_BAG_MODAL_SHOW'; // 显示红包弹窗
export const TASKS_GET_AWARD_REQUEST = 'TASKS_GET_AWARD_REQUEST'; // 领取红包

// 获取网赚用户的用户信息
export const TASKS_WANGZHUAN_USER_INFO_REQUEST = 'TASKS_WANGZHUAN_USER_INFO_REQUEST'
export const TASKS_WANGZHUAN_USER_INFO_SUCCESS = 'TASKS_WANGZHUAN_USER_INFO_SUCCESS'
export const TASKS_WANGZHUAN_USER_INFO_FAILURE = 'TASKS_WANGZHUAN_USER_INFO_FAILURE'

// 获取师徒红包信息
export const TASKS_GET_INVITE_RED_BAG_REQUEST = 'TASKS_GET_INVITE_RED_BAG_REQUEST';
export const TASKS_GET_INVITE_RED_BAG_SUCCESS = 'TASKS_GET_INVITE_RED_BAG_SUCCESS';
export const TASKS_GET_INVITE_RED_BAG_FAILURE = 'TASKS_GET_INVITE_RED_BAG_FAILURE';

// 师傅红包统计
export const TASKS_INVITE_STATS_REQUEST = 'TASKS_INVITE_STATS_REQUEST';
export const TASKS_INVITE_STATS_SUCCESS = 'TASKS_INVITE_STATS_SUCCESS';
export const TASKS_INVITE_STATS_FAILURE = 'TASKS_INVITE_STATS_FAILURE';

export const TASKS_INVITE_MODAL_SHOW = 'TASKS_INVITE_MODAL_SHOW';
export const TASKS_INVITE_MODAL_HIDE = 'TASKS_INVITE_MODAL_HIDE';

export const TASKS_SHOW_INFO_MODAL = 'TASKS_SHOW_INFO_MODAL'; // 展示消息确认弹框

// 开始领取任务并计时
export const TASKS_START_TIME_REQUEST = 'TASKS_START_TIME_REQUEST'
export const TASKS_START_TIME_SUCCESS = 'TASKS_START_TIME_SUCCESS'
export const TASKS_START_TIME_FAILURE = 'TASKS_START_TIME_FAILURE'

// 是否显示中断计时弹框
export const TASKS_SHOW_INTERRUPT_MODAL = 'TASKS_SHOW_INTERRUPT_MODAL'
export const TASKS_HIDE_INTERRUPT_MODAL = 'TASKS_HIDE_INTERRUPT_MODAL'

// 中断计时
export const TASKS_INTERRUPT_TIME_REQUEST = 'TASKS_INTERRUPT_TIME_REQUEST';
export const TASKS_AUTO_INTERRUPT_TIME = 'TASKS_AUTO_INTERRUPT_TIME';

// 新手任务列表详情
export const TASKS_NOVICE_TASKS_REQUEST = 'TASKS_NOVICE_TASKS_REQUEST'
export const TASKS_NOVICE_TASKS_SUCCESS = 'TASKS_NOVICE_TASKS_SUCCESS'
export const TASKS_NOVICE_TASKS_FAILURE = 'TASKS_NOVICE_TASKS_FAILURE'

export const TASK_DISPLAY_NOVICE_TASKS_MODAL = 'TASK_DISPLAY_NOVICE_TASKS_MODAL'; // 展示新手引导弹框
export const TASKS_GET_NOVICE_TASKS_AWARD = 'TASKS_GET_NOVICE_TASKS_AWARD'; // 领取新手任务列表奖励

// 获取新手任务剩余未领取金额
export const TASKS_REST_NOVICE_AWARD_REQUEST = 'TASKS_REST_NOVICE_AWARD_REQUEST';
export const TASKS_REST_NOVICE_AWARD_SUCCESS = 'TASKS_REST_NOVICE_AWARD_SUCCESS';
export const TASKS_REST_NOVICE_AWARD_FAILURE = 'TASKS_REST_NOVICE_AWARD_FAILURE';
/* 网赚任务 end */

/*九宫格抽奖*/
export const LOTTERY_INIT_REQUEST = 'LOTTERY_INIT_REQUEST';
export const LOTTERY_INIT_SUCCESS = 'LOTTERY_INIT_SUCCESS';
export const LOTTERY_INIT_FAILURE = 'LOTTERY_INIT_FAILURE';

export const LOTTERY_GET_TIMES_REQUEST = 'LOTTERY_GET_TIMES_REQUEST';
export const LOTTERY_GET_TIMES_SUCCESS = 'LOTTERY_GET_TIMES_SUCCESS';
export const LOTTERY_GET_TIMES_FAILURE = 'LOTTERY_GET_TIMES_FAILURE';

export const LOTTERY_DO_PLAY_REQUEST = 'LOTTERY_DO_PLAY_REQUEST';
export const LOTTERY_DO_PLAY_SUCCESS = 'LOTTERY_DO_PLAY_SUCCESS';
export const LOTTERY_DO_PLAY_FAILURE = 'LOTTERY_DO_PLAY_FAILURE';

export const LOTTERY_RED_BAG = 'LOTTERY_RED_BAG';
